<a href="https://colab.research.google.com/github/thucuyen127/baitap/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import random

def taomatran(m,n): #Hàm tạo ma trận m hàng n cột
  a = np.random.randint(-10,10,(m,n))
  return a
m=int(input('m = '))
n=int(input('n = '))
p=int(input('p = '))
a = taomatran(m,n)
b = taomatran(n,p)
c = taomatran(m,n)
print('A = \n',a)
print('B = \n',b)
print('C = \n',c)
print('A + C = \n',a + c)
print('A - C = \n',a - c)
print('A * B = \n',a @ B)
print('A * 5 = \n',a * 5)
print('A / 5 = \n',a / 5)
print('ma tran chuyen vi cua A:\n',np.transpose(a))


m = 2
n = 3
p = 4
A = 
 [[  3  -6   1]
 [  4   4 -10]]
B = 
 [[ -8 -10  -7  -3]
 [  9   8   4   1]
 [  0  -5  -2   7]]
C = 
 [[ -6   0   8]
 [-10  -7   8]]
A + C = 
 [[-3 -6  9]
 [-6 -3 -2]]
A - C = 
 [[  9  -6  -7]
 [ 14  11 -18]]
A * B = 
 [[ -6247 -26228 -12272]
 [  1354  15554   7610]]
A * 5 = 
 [[ 15 -30   5]
 [ 20  20 -50]]
A / 5 = 
 [[ 0.6 -1.2  0.2]
 [ 0.8  0.8 -2. ]]
ma tran chuyen vi cua A:
 [[  3   4]
 [ -6   4]
 [  1 -10]]
